name: Makefile CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Change Dir
      run: cd caesarplus
      
    - name: Install
      run: make install

    - name: Test
      run: make test
